name: Delpoy first html file to EC2

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show all files
        run: ls -al

      - name: Doing SSH to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH }}
          port: 22
          script: |
            whoami
            pwd
            mkdir noizy
            ls -al

      - name: Upload files to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH }}
          port: 22
          source: "index.html"
          target: "/home/ubuntu"
          script: |
            cp "/home/ubuntu/index.html" "/var/www/html/index.html"
